name: image-devenv-main-arm64
run-name: "[ref:${{ github.ref }}] [user:${{ github.actor }}]"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths:
      - images/devenv-main-arm64/**
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup-docker-buildx
        uses: docker/setup-buildx-action@v2

      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/whiterabbit7516/devcontainers/devenv-main-arm64
          imageName: ghcr.io/whiterabbit7516/devcontainers/devenv-main-arm64
          platform: linux/arm64
          push: always
          subFolder: images/devenv-main-arm64/



